---
title: "Défi sportif de la Direction de la méthodologie 2018"
author: "1"
date: "2018 Methodology Branch Physical Activity Challenge"
output:
  revealjs::revealjs_presentation:
    center: yes
    theme: night
    transition: fade
    css: my-style.css
---

```{r setup, echo=FALSE, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE);
require(dplyr);
require(ggplot2);
require(kableExtra);
require(knitr);
require(RColorBrewer);
require(readr);
require(tidyr);

DIR.data <- ".";

textsize.axis   = 18;
textsize.legend = 18;
textsize.title  = 25;

string.week <- "Semaine / Week";
my.palette <- brewer.pal(n=4,name="YlOrRd");
names(my.palette) <- paste0(string.week," ",seq(1,4,1));
```

```{r loadWideData, echo=FALSE, include=FALSE, message=FALSE}
CSV.branch.wide <- file.path(DIR.data,"weekly-scores-section.csv");
DF.branch.wide  <- read_csv(file = CSV.branch.wide);
DF.branch.wide  <- DF.branch.wide %>%
    mutate(Section = paste0(division,":",chief));

DF.branch.wide <- as.data.frame(DF.branch.wide);

DF.branch.wide[,"division"] <- factor(x=gsub(
    x           = as.character(DF.branch.wide[,"division"]),
    pattern     = "/",
    replacement = " / "
    ));

colnames(DF.branch.wide) <- gsub(
    x           = colnames(DF.branch.wide),
    pattern     = "week",
    replacement = paste0(string.week," ")
    );

DF.branch.long <- as.data.frame(gather(
    data  = DF.branch.wide,
    key   = week,
    value = score,
    names(my.palette)
    ));
```

<!--
## Week of May 28, 2018 {#showBarChart}
-->
```{r showBarChart, echo=FALSE, message=FALSE, fig.width=12, fig.height=6}
my.ggplot <- ggplot(data = NULL) + theme_bw();

my.ggplot <- my.ggplot + theme(
    title             = element_text(size = textsize.title, face = "bold"),
    plot.background   = element_rect(fill = "black", colour = "black"),
    axis.title.x      = element_blank(),
    axis.title.y      = element_blank(),
    axis.text.x       = element_text(size=textsize.axis,face="bold",color="gray",angle=90,vjust=0.5),
    axis.text.y       = element_text(size=textsize.axis,face="bold",color="gray"),
    panel.background  = element_rect(fill = "black", colour = "black"),
    panel.grid.major  = element_line(colour="gray", linetype=2, size=0.50),
    panel.grid.minor  = element_line(colour="gray", linetype=2, size=0.50),
    legend.position   = "bottom",
    legend.title      = element_blank(),
    legend.direction  = "horizontal",
    legend.key        = element_rect(fill=alpha('white',0)),
    legend.text       = element_text(size=textsize.legend,face="bold",color="gray",margin=margin(l=24,r=24,unit="pt")),
    legend.background = element_rect(fill=alpha('white',0)),
    legend.key.size   = unit(1,"cm"),
    legend.spacing    = unit(1,"cm"),
    legend.margin     = margin(t = 1, r = 1, b = 1, l = 1, unit = "pt"),
    strip.text        = element_text(size=textsize.axis,colour="black")
    );

my.ggplot <- my.ggplot + scale_y_continuous(limits=1000*c(0,6),breaks=1000*seq(0,6,1));

my.ggplot <- my.ggplot + scale_fill_manual(
    values = my.palette,
    labels = paste0(names(my.palette),paste0(rep(" ",4),collapse=""))
    );

my.ggplot <- my.ggplot + geom_col(
    data     = DF.branch.long,
    mapping  = aes(y=score,x=chief,fill=week),
    position = position_stack(reverse = TRUE)
    );

my.ggplot <- my.ggplot + facet_grid( ~ division, scales = "free_x");

ggsave(filename=file.path(DIR.data,"barchart-sections.png"),plot=my.ggplot,device="png")

my.ggplot;
```
